"""add precificacao tables

Revision ID: 8ebb6229bdeb
Revises: 20260325_orig_item_id
Create Date: 2026-03-26 17:09:01.555084
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8ebb6229bdeb'
down_revision = '20260325_orig_item_id'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agendamentos', 'tem_intercorrencia',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('atendimentos_clinicos', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('empresas', 'ativa',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('empresas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('empresas_cnpj_key'), 'empresas', type_='unique')
    op.alter_column('pdv_pagamentos', 'quantidade_parcelas',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_pdv_venda_itens_gera_movimento_estoque'), 'pdv_venda_itens', ['gera_movimento_estoque'], unique=False)
    op.create_index(op.f('ix_pdv_venda_itens_origem_item'), 'pdv_venda_itens', ['origem_item'], unique=False)
    op.create_foreign_key(None, 'pdv_venda_itens', 'produtos', ['produto_id'], ['id'])
    op.alter_column('pdv_vendas', 'caixa_sessao_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pet_exames', 'nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               nullable=True)
    op.alter_column('pet_exames', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_pet_exames_pet_id'), table_name='pet_exames')
    op.drop_constraint(op.f('pet_exames_pet_id_fkey'), 'pet_exames', type_='foreignkey')
    op.drop_column('pet_exames', 'updated_at')
    op.drop_column('pet_exames', 'pet_id')
    op.drop_column('pet_exames', 'status')
    op.alter_column('pet_receitas', 'descricao',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('pet_receitas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_pet_receitas_pet_id'), table_name='pet_receitas')
    op.drop_constraint(op.f('pet_receitas_pet_id_fkey'), 'pet_receitas', type_='foreignkey')
    op.drop_column('pet_receitas', 'updated_at')
    op.drop_column('pet_receitas', 'pet_id')
    op.alter_column('producao', 'coluna',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('producao', 'etapa_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('producao', 'prioridade',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('producao', 'finalizado',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('producao', 'aguardando_pdv',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('producao', 'enviado_pdv',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('producao', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('producao', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('producao_agendamento_id_key'), 'producao', type_='unique')
    op.create_index(op.f('ix_producao_agendamento_id'), 'producao', ['agendamento_id'], unique=True)
    op.create_index(op.f('ix_producao_id'), 'producao', ['id'], unique=False)
    op.alter_column('produtos', 'custo_medio_atual',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               server_default='0',
               existing_nullable=False)
    op.alter_column('produtos', 'aliquota_icms',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default='0',
               existing_nullable=False)
    op.alter_column('produtos', 'aliquota_pis',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default='0',
               existing_nullable=False)
    op.alter_column('produtos', 'aliquota_cofins',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default='0',
               existing_nullable=False)
    op.create_index(op.f('ix_produtos_ncm'), 'produtos', ['ncm'], unique=False)
    op.alter_column('servicos', 'tipo_servico',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_servicos_tipo_servico'), 'servicos', ['tipo_servico'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicos_tipo_servico'), table_name='servicos')
    op.alter_column('servicos', 'tipo_servico',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'PETSHOP'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_produtos_ncm'), table_name='produtos')
    op.alter_column('produtos', 'aliquota_cofins',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('produtos', 'aliquota_pis',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('produtos', 'aliquota_icms',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('produtos', 'custo_medio_atual',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_producao_id'), table_name='producao')
    op.drop_index(op.f('ix_producao_agendamento_id'), table_name='producao')
    op.create_unique_constraint(op.f('producao_agendamento_id_key'), 'producao', ['agendamento_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('producao', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('producao', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('producao', 'enviado_pdv',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('producao', 'aguardando_pdv',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('producao', 'finalizado',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('producao', 'prioridade',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'NORMAL'::character varying"),
               existing_nullable=False)
    op.alter_column('producao', 'etapa_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'AGUARDANDO'::character varying"),
               existing_nullable=False)
    op.alter_column('producao', 'coluna',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'PRE_BANHO'::character varying"),
               existing_nullable=False)
    op.add_column('pet_receitas', sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pet_receitas', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('pet_receitas_pet_id_fkey'), 'pet_receitas', 'pets', ['pet_id'], ['id'])
    op.create_index(op.f('ix_pet_receitas_pet_id'), 'pet_receitas', ['pet_id'], unique=False)
    op.alter_column('pet_receitas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pet_receitas', 'descricao',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('pet_exames', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('pet_exames', sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pet_exames', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('pet_exames_pet_id_fkey'), 'pet_exames', 'pets', ['pet_id'], ['id'])
    op.create_index(op.f('ix_pet_exames_pet_id'), 'pet_exames', ['pet_id'], unique=False)
    op.alter_column('pet_exames', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pet_exames', 'nome',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('pdv_vendas', 'caixa_sessao_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'pdv_venda_itens', type_='foreignkey')
    op.drop_index(op.f('ix_pdv_venda_itens_origem_item'), table_name='pdv_venda_itens')
    op.drop_index(op.f('ix_pdv_venda_itens_gera_movimento_estoque'), table_name='pdv_venda_itens')
    op.alter_column('pdv_pagamentos', 'quantidade_parcelas',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('empresas_cnpj_key'), 'empresas', ['cnpj'], postgresql_nulls_not_distinct=False)
    op.alter_column('empresas', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('empresas', 'ativa',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('atendimentos_clinicos', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('agendamentos', 'tem_intercorrencia',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###